// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Generated by Database Inspector on 2026-03-01T20:57:17Z
// Re-generate by running: SELECT get_full_schema_dump(); in Supabase SQL Editor
// Then paste the output as the value of SCHEMA_SNAPSHOT below

export const SCHEMA_SNAPSHOT = `# SUPABASE LIVE DATABASE SCHEMA
# Generated: 2026-03-01 20:57:17.606226+00
# Schema: public
========================================

## TABLE: admin_emails (1 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  email — text NOT NULL
  created_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: admin_emails_email_key
RLS: Only admins can delete admin_emails (DELETE)
RLS: Only admins can insert admin_emails (INSERT)
RLS: Only admins can read admin_emails (SELECT)
RLS: Only admins can update admin_emails (UPDATE)

## TABLE: analytics_events (330 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  session_id — text NOT NULL
  event_type — text NOT NULL
  event_category — text
  event_label — text
  event_value — numeric
  page_path — text
  referrer — text
  utm_source — text
  utm_medium — text
  utm_campaign — text
  utm_term — text
  utm_content — text
  user_agent — text
  screen_width — integer
  screen_height — integer
  metadata — jsonb DEFAULT '{}'::jsonb
  created_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: idx_analytics_events_session
INDEX: idx_analytics_events_type
INDEX: idx_analytics_events_created
INDEX: idx_analytics_events_category
RLS: Anyone can insert analytics events (INSERT)
RLS: Only admins can delete analytics events (DELETE)
RLS: Only admins can read analytics events (SELECT)
ENUM VALUES [event_category]: form, navigation
ENUM VALUES [event_type]: form_view, page_view

## TABLE: analytics_sessions (56 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  session_id — text NOT NULL
  first_page — text
  last_page — text
  referrer — text
  utm_source — text
  utm_medium — text
  utm_campaign — text
  user_agent — text
  screen_width — integer
  screen_height — integer
  page_count — integer DEFAULT 1
  event_count — integer DEFAULT 0
  is_bounce — boolean DEFAULT true
  started_at — timestamp with time zone NOT NULL DEFAULT now()
  last_activity_at — timestamp with time zone NOT NULL DEFAULT now()
  duration_seconds — integer DEFAULT 0
PRIMARY KEY: id
INDEX: analytics_sessions_session_id_key
INDEX: idx_analytics_sessions_started
INDEX: idx_analytics_sessions_source
RLS: Anyone can insert analytics sessions (INSERT)
RLS: Anyone can update analytics sessions (UPDATE)
RLS: Only admins can delete analytics sessions (DELETE)
RLS: Only admins can read analytics sessions (SELECT)

## TABLE: blog_posts (3 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  title — text NOT NULL
  slug — text NOT NULL
  excerpt — text
  content — text NOT NULL
  cover_image_url — text
  author_name — text NOT NULL DEFAULT 'FitMatch Team'::text
  category — text
  tags — ARRAY DEFAULT '{}'::text[]
  status — text NOT NULL DEFAULT 'draft'::text
  published_at — timestamp with time zone
  meta_title — text
  meta_description — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: blog_posts_slug_key
INDEX: idx_blog_slug
INDEX: idx_blog_status
INDEX: idx_blog_published
RLS: Admins can delete blog posts (DELETE)
RLS: Admins can insert blog posts (INSERT)
RLS: Admins can read all blog posts (SELECT)
RLS: Admins can update blog posts (UPDATE)
RLS: Anyone can read published blog posts (SELECT)
TRIGGER: trg_update_blog_post_updated_at
TRIGGER: trg_validate_blog_post_fields
ENUM VALUES [category]: Buying Guide, Renovation Tips
ENUM VALUES [status]: draft

## TABLE: categories (7 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  name — text NOT NULL
  slug — text NOT NULL
  description — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: categories_name_key
INDEX: categories_slug_key
RLS: Admin users can delete categories (DELETE)
RLS: Admin users can insert categories (INSERT)
RLS: Admin users can update categories (UPDATE)
RLS: Categories are publicly readable (SELECT)

## TABLE: communication_logs (1 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  direction — text NOT NULL
  user_id — uuid
  user_email — text NOT NULL
  user_type — text
  template_key — text
  subject — text NOT NULL
  html_body — text
  plain_text_body — text
  from_address — text NOT NULL
  to_address — text NOT NULL
  reply_to — text
  mailgun_message_id — text
  status — text DEFAULT 'queued'::text
  metadata — jsonb DEFAULT '{}'::jsonb
  related_entity_type — text
  related_entity_id — uuid
  locale — text DEFAULT 'en-CA'::text
  pinecone_synced — boolean DEFAULT false
  error_message — text
  opened_at — timestamp with time zone
  clicked_at — timestamp with time zone
  created_at — timestamp with time zone DEFAULT now()
PRIMARY KEY: id
FK: user_id -> profiles(id)
INDEX: idx_comm_logs_user
INDEX: idx_comm_logs_entity
INDEX: idx_comm_logs_pinecone
INDEX: idx_comm_logs_status
RLS: Admins can manage all communication logs (ALL)
RLS: Users can read own communication logs (SELECT)
TRIGGER: trg_validate_communication_log
ENUM VALUES [direction]: outbound
ENUM VALUES [locale]: en-CA
ENUM VALUES [status]: sent
ENUM VALUES [template_key]: account_welcome
ENUM VALUES [user_type]: client

## TABLE: consent_logs (2 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  session_id — text NOT NULL
  ip_hash — text
  action — text NOT NULL
  categories — jsonb NOT NULL DEFAULT '{}'::jsonb
  user_agent — text
  page_url — text
  banner_version — text DEFAULT '1.0'::text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
RLS: Admins can read consent logs (SELECT)
RLS: Anyone can insert consent logs (INSERT)

## TABLE: contractor_details (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL
  trade_types — ARRAY NOT NULL DEFAULT '{}'::text[]
  service_areas — ARRAY NOT NULL DEFAULT '{}'::text[]
  years_experience — integer
  portfolio_url — text
  bio — text
  is_verified — boolean DEFAULT false
  rating — numeric DEFAULT 0
  jobs_completed — integer DEFAULT 0
PRIMARY KEY: id
FK: id -> profiles(id)
RLS: Contractors can manage own details (ALL)
RLS: Public can read contractor details (SELECT)

## TABLE: cookie_categories (3 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  name — text NOT NULL
  slug — text NOT NULL
  description — text NOT NULL DEFAULT ''::text
  is_required — boolean NOT NULL DEFAULT false
  is_default — boolean NOT NULL DEFAULT false
  sort_order — integer NOT NULL DEFAULT 0
  is_active — boolean NOT NULL DEFAULT true
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: cookie_categories_slug_key
RLS: Admins can manage cookie categories (ALL)
RLS: Cookie categories are publicly readable (SELECT)
TRIGGER: update_cookie_categories_updated_at

## TABLE: cookie_definitions (7 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  category_id — uuid NOT NULL
  name — text NOT NULL
  provider — text NOT NULL DEFAULT ''::text
  purpose — text NOT NULL DEFAULT ''::text
  duration — text NOT NULL DEFAULT 'Session'::text
  type — text NOT NULL DEFAULT 'First-party'::text
  is_active — boolean NOT NULL DEFAULT true
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
FK: category_id -> cookie_categories(id)
RLS: Admins can manage cookie definitions (ALL)
RLS: Cookie definitions are publicly readable (SELECT)
TRIGGER: update_cookie_definitions_updated_at
ENUM VALUES [type]: First-party, Third-party

## TABLE: email_consent_log (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  user_id — uuid
  email — text NOT NULL
  consent_type — text NOT NULL
  consent_category — text NOT NULL
  granted — boolean NOT NULL
  consent_text — text NOT NULL
  source — text NOT NULL
  ip_address — text
  user_agent — text
  created_at — timestamp with time zone DEFAULT now()
PRIMARY KEY: id
FK: user_id -> profiles(id)
RLS: Admins can read all email consent logs (SELECT)
RLS: Anyone can insert consent logs (INSERT)
RLS: Users can read own consent logs (SELECT)
TRIGGER: trg_validate_email_consent_log

## TABLE: email_templates (20 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  template_key — text NOT NULL
  category — text NOT NULL DEFAULT 'transactional'::text
  customer_type — text NOT NULL DEFAULT 'client'::text
  display_name — text NOT NULL
  subject — text NOT NULL
  html_body — text NOT NULL
  plain_text_body — text
  from_email — text DEFAULT 'orders@fitmatch.ca'::text
  from_name — text DEFAULT 'FitMatch'::text
  reply_to — text DEFAULT 'support@fitmatch.ca'::text
  locale — text DEFAULT 'en-CA'::text
  variables_schema — jsonb DEFAULT '[]'::jsonb
  is_active — boolean DEFAULT true
  requires_consent — boolean DEFAULT false
  casl_category — text DEFAULT 'transactional'::text
  version — integer DEFAULT 1
  created_at — timestamp with time zone DEFAULT now()
  updated_at — timestamp with time zone DEFAULT now()
PRIMARY KEY: id
INDEX: email_templates_template_key_key
RLS: Active templates are publicly readable (SELECT)
RLS: Admins can manage email templates (ALL)
TRIGGER: trg_email_templates_updated_at
TRIGGER: trg_validate_email_template
ENUM VALUES [casl_category]: express, implied, transactional
ENUM VALUES [category]: lifecycle, marketing, operational, transactional
ENUM VALUES [customer_type]: all, client
ENUM VALUES [locale]: en-CA
ENUM VALUES [template_key]: abandoned_cart, account_welcome, admin_alert, appliance_recommendation, contractor_followup, contractor_matched, countertop_followup, new_inventory_alert, newsletter, order_confirmation, order_delivered, order_shipped, password_reset, payment_failed, payment_receipt, project_update, quote_response, refund_processed, review_request, seasonal_promotion

## TABLE: faq_items (16 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  group_id — text NOT NULL
  group_title — text NOT NULL
  question — text NOT NULL
  answer — text NOT NULL
  sort_order — integer NOT NULL DEFAULT 0
  is_active — boolean NOT NULL DEFAULT true
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
RLS: FAQ items are publicly readable (SELECT)
RLS: Only admins can delete faq items (DELETE)
RLS: Only admins can insert faq items (INSERT)
RLS: Only admins can update faq items (UPDATE)
TRIGGER: update_faq_items_updated_at

## TABLE: footer_pages (20 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  slug — text NOT NULL
  title — text NOT NULL
  section — text NOT NULL
  content — text NOT NULL DEFAULT ''::text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: footer_pages_slug_key
RLS: Footer pages are publicly readable (SELECT)
RLS: Only admins can delete footer pages (DELETE)
RLS: Only admins can insert footer pages (INSERT)
RLS: Only admins can update footer pages (UPDATE)
TRIGGER: update_footer_pages_updated_at

## TABLE: integrations (7 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  service_name — text NOT NULL
  display_name — text NOT NULL
  category — text NOT NULL
  is_enabled — boolean NOT NULL DEFAULT false
  status — text NOT NULL DEFAULT 'disconnected'::text
  last_health_check — timestamp with time zone
  last_health_status — text DEFAULT 'unknown'::text
  config — jsonb NOT NULL DEFAULT '{}'::jsonb
  encrypted_credentials — jsonb DEFAULT '{}'::jsonb
  webhook_url — text
  notes — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: integrations_service_name_key
RLS: Only admins can manage integrations (ALL)
TRIGGER: update_integrations_updated_at
TRIGGER: validate_integration_fields_trigger
ENUM VALUES [category]: automation, chatbot, email, marketing, payment, voice
ENUM VALUES [last_health_status]: unknown
ENUM VALUES [status]: disconnected

## TABLE: newsletter_subscribers (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  email — text NOT NULL
  name — text
  source — text NOT NULL DEFAULT 'footer'::text
  consent_text — text NOT NULL
  is_active — boolean NOT NULL DEFAULT true
  subscribed_at — timestamp with time zone NOT NULL DEFAULT now()
  unsubscribed_at — timestamp with time zone
PRIMARY KEY: id
INDEX: newsletter_subscribers_email_key
INDEX: idx_newsletter_email
RLS: Admins can delete newsletter subscribers (DELETE)
RLS: Admins can read newsletter subscribers (SELECT)
RLS: Admins can update newsletter subscribers (UPDATE)
RLS: Anyone can insert newsletter subscribers (INSERT)

## TABLE: order_items (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  order_id — uuid NOT NULL
  product_id — uuid
  product_name — text NOT NULL
  product_sku — text
  product_image — text
  quantity — integer NOT NULL DEFAULT 1
  unit_price — numeric NOT NULL
  total_price — numeric NOT NULL
  metadata — jsonb DEFAULT '{}'::jsonb
  created_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
FK: product_id -> products(id)
FK: order_id -> orders(id)
RLS: Admins can manage all order items (ALL)
RLS: Anyone can insert order items (INSERT)
RLS: Users can view own order items (SELECT)
TRIGGER: validate_order_item_quantity_trigger

## TABLE: orders (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  order_number — text NOT NULL
  user_id — uuid
  guest_email — text
  status — text NOT NULL DEFAULT 'pending'::text
  subtotal — numeric NOT NULL DEFAULT 0
  shipping_cost — numeric NOT NULL DEFAULT 0
  tax_amount — numeric NOT NULL DEFAULT 0
  tax_rate — numeric NOT NULL DEFAULT 0.13
  total — numeric NOT NULL DEFAULT 0
  currency — text NOT NULL DEFAULT 'CAD'::text
  shipping_name — text NOT NULL
  shipping_address_line_1 — text NOT NULL
  shipping_address_line_2 — text
  shipping_city — text NOT NULL
  shipping_province — text NOT NULL
  shipping_postal_code — text NOT NULL
  shipping_country — text NOT NULL DEFAULT 'CA'::text
  shipping_phone — text
  shipping_method — text DEFAULT 'standard'::text
  stripe_payment_intent_id — text
  stripe_checkout_session_id — text
  payment_status — text NOT NULL DEFAULT 'unpaid'::text
  paid_at — timestamp with time zone
  tracking_number — text
  tracking_url — text
  estimated_delivery — text
  notes — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: orders_order_number_key
RLS: Admins can manage all orders (ALL)
RLS: Anyone can create orders (INSERT)
RLS: Users can view own orders (SELECT)
TRIGGER: set_order_number
TRIGGER: update_orders_updated_at
TRIGGER: validate_order_status_trigger

## TABLE: product_reviews (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  product_id — uuid NOT NULL
  user_id — uuid NOT NULL
  reviewer_name — text NOT NULL
  rating — integer NOT NULL
  title — text
  body — text
  status — text NOT NULL DEFAULT 'pending'::text
  admin_note — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
FK: product_id -> products(id)
INDEX: idx_reviews_product
INDEX: idx_reviews_status
RLS: Admins can delete reviews (DELETE)
RLS: Admins can read all reviews (SELECT)
RLS: Admins can update reviews (UPDATE)
RLS: Anyone can read approved reviews (SELECT)
RLS: Authenticated users can insert own reviews (INSERT)
RLS: Users can read own reviews (SELECT)
TRIGGER: trg_update_review_updated_at
TRIGGER: trg_validate_review_fields

## TABLE: products (9 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  product_name — text NOT NULL
  product_code — text NOT NULL
  category_id — uuid
  style — text NOT NULL
  color — text NOT NULL
  material — text NOT NULL
  width_mm — integer NOT NULL
  height_mm — integer NOT NULL
  depth_mm — integer NOT NULL
  price_retail_usd — numeric NOT NULL
  price_discounted_usd — numeric NOT NULL
  discount_percentage — numeric NOT NULL DEFAULT 0
  short_description — text
  long_description — text
  main_image_url — text
  additional_image_urls — ARRAY DEFAULT '{}'::text[]
  stock_level — integer NOT NULL DEFAULT 0
  availability_status — text NOT NULL DEFAULT 'In Stock'::text
  is_featured — boolean NOT NULL DEFAULT false
  compatible_kitchen_layouts — ARRAY DEFAULT '{}'::text[]
  installation_instructions_url — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
  tag — text
  manufacturer — text
  countertop_option — text DEFAULT 'no'::text
  countertop_material — text
  countertop_thickness — text
  countertop_finish — text
  countertop_stock — integer DEFAULT 0
  countertop_included — boolean DEFAULT false
  countertop_price_retail — numeric DEFAULT 0
  countertop_price_discounted — numeric DEFAULT 0
  countertop_discount_percentage — numeric DEFAULT 0
  deleted_at — timestamp with time zone
  seller_id — uuid
  width_inches — numeric
  depth_inches — numeric
  height_inches — numeric
PRIMARY KEY: id
FK: seller_id -> profiles(id)
FK: category_id -> categories(id)
INDEX: products_product_code_key
INDEX: idx_products_featured
INDEX: idx_products_category
INDEX: idx_products_style
INDEX: idx_products_availability
INDEX: idx_products_seller
RLS: Admin users can delete products (DELETE)
RLS: Admin users can insert products (INSERT)
RLS: Admin users can update products (UPDATE)
RLS: Products are publicly readable (SELECT)
RLS: Sellers can insert own products (INSERT)
RLS: Sellers can read own products (SELECT)
RLS: Sellers can update own products (UPDATE)
TRIGGER: update_products_updated_at
ENUM VALUES [availability_status]: Deactivated, In Stock, Low Stock

## TABLE: profiles (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL
  user_type — text NOT NULL
  full_name — text NOT NULL
  email — text NOT NULL
  phone — text
  company_name — text
  location — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
RLS: Admins can read all profiles (SELECT)
RLS: Users can insert own profile (INSERT)
RLS: Users can read own profile (SELECT)
RLS: Users can update own profile (UPDATE)
TRIGGER: update_profiles_updated_at

## TABLE: project_contractors (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  project_id — uuid NOT NULL
  contractor_id — uuid NOT NULL
  trade_type — text NOT NULL
  status — text NOT NULL DEFAULT 'pending'::text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
FK: project_id -> projects(id)
FK: contractor_id -> profiles(id)
RLS: Project participants can view (SELECT)
TRIGGER: trg_validate_project_contractor_status

## TABLE: projects (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  client_id — uuid NOT NULL
  product_id — uuid
  status — text NOT NULL DEFAULT 'draft'::text
  opening_width_mm — integer
  opening_height_mm — integer
  opening_depth_mm — integer
  notes — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
FK: product_id -> products(id)
FK: client_id -> profiles(id)
RLS: Clients can manage own projects (ALL)
TRIGGER: trg_validate_project_status

## TABLE: quote_request_items (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  quote_request_id — uuid NOT NULL
  product_id — uuid
  product_name — text NOT NULL
  quantity — integer NOT NULL DEFAULT 1
  notes — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
FK: quote_request_id -> quote_requests(id)
FK: product_id -> products(id)
RLS: Admins can manage all quote items (ALL)
RLS: Anyone can insert quote items (INSERT)
RLS: Users can view own quote items (SELECT)

## TABLE: quote_requests (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  quote_number — text NOT NULL
  user_id — uuid
  contact_name — text NOT NULL
  contact_email — text NOT NULL
  contact_phone — text
  company_name — text
  project_type — text
  project_timeline — text
  delivery_address — text
  notes — text
  status — text NOT NULL DEFAULT 'new'::text
  admin_notes — text
  quoted_total — numeric
  quoted_at — timestamp with time zone
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: quote_requests_quote_number_key
RLS: Admins can manage all quotes (ALL)
RLS: Anyone can create quote requests (INSERT)
RLS: Users can view own quotes (SELECT)
TRIGGER: set_quote_number
TRIGGER: update_quote_requests_updated_at
TRIGGER: validate_quote_request_status_v2_trigger

## TABLE: shipping_addresses (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  user_id — uuid
  full_name — text NOT NULL
  address_line_1 — text NOT NULL
  address_line_2 — text
  city — text NOT NULL
  province — text NOT NULL
  postal_code — text NOT NULL
  country — text NOT NULL DEFAULT 'CA'::text
  phone — text
  is_default — boolean NOT NULL DEFAULT false
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
RLS: Users can manage their own addresses (ALL)
TRIGGER: update_shipping_addresses_updated_at

## TABLE: site_settings (28 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  key — text NOT NULL
  value — text NOT NULL DEFAULT ''::text
  description — text
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
INDEX: site_settings_key_key
RLS: Admins can delete site settings (DELETE)
RLS: Admins can insert site settings (INSERT)
RLS: Admins can update site settings (UPDATE)
RLS: Site settings are publicly readable (SELECT)
TRIGGER: update_site_settings_updated_at

## TABLE: trust_signals (7 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  type — text NOT NULL
  icon_name — text NOT NULL
  title — text NOT NULL
  label — text NOT NULL
  sort_order — integer NOT NULL DEFAULT 0
  is_active — boolean NOT NULL DEFAULT true
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  updated_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
RLS: Only admins can delete trust signals (DELETE)
RLS: Only admins can insert trust signals (INSERT)
RLS: Only admins can update trust signals (UPDATE)
RLS: Trust signals are publicly readable (SELECT)
TRIGGER: update_trust_signals_updated_at
ENUM VALUES [type]: guarantee, stat

## TABLE: webhook_logs (11 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  event_type — text NOT NULL
  direction — text NOT NULL
  webhook_url — text NOT NULL
  request_payload — jsonb
  response_status — integer
  response_body — text
  duration_ms — integer
  status — text NOT NULL DEFAULT 'pending'::text
  retry_count — integer NOT NULL DEFAULT 0
  max_retries — integer NOT NULL DEFAULT 3
  next_retry_at — timestamp with time zone
  error_message — text
  created_at — timestamp with time zone NOT NULL DEFAULT now()
  integration_id — uuid
PRIMARY KEY: id
FK: integration_id -> integrations(id)
INDEX: idx_webhook_logs_event_type
INDEX: idx_webhook_logs_status
INDEX: idx_webhook_logs_created_at
INDEX: idx_webhook_logs_integration
RLS: Only admins can view webhook logs (ALL)
TRIGGER: validate_webhook_log_fields_trigger
ENUM VALUES [direction]: outbound
ENUM VALUES [event_type]: health.check.test, order.created.test
ENUM VALUES [status]: delivered, failed

## TABLE: wishlists (0 rows)
----------------------------------------
COLUMNS:
  id — uuid NOT NULL DEFAULT gen_random_uuid()
  user_id — uuid NOT NULL
  product_id — uuid NOT NULL
  created_at — timestamp with time zone NOT NULL DEFAULT now()
PRIMARY KEY: id
FK: product_id -> products(id)
INDEX: wishlists_user_id_product_id_key
INDEX: idx_wishlists_user
RLS: Admins can read all wishlists (SELECT)
RLS: Users can delete own wishlist items (DELETE)
RLS: Users can insert own wishlist items (INSERT)
RLS: Users can read own wishlist (SELECT)

## RPC FUNCTIONS:
  generate_order_number()
  generate_quote_number()
  get_full_schema_dump()
  handle_new_user()
  is_admin()
`;

export const SCHEMA_GENERATED_AT = "2026-03-01T20:57:17Z";
